"""initial

Revision ID: d24cf0da66c8
Revises: 
Create Date: 2020-11-07 18:45:18.985032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d24cf0da66c8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate",
        sa.Column("id", sa.Integer(), nullable=False, comment="Rate ID"),
        sa.Column(
            "source_currency",
            sa.String(),
            nullable=False,
            comment="Source currency code",
        ),
        sa.Column(
            "target_currency",
            sa.String(),
            nullable=False,
            comment="Target currency code",
        ),
        sa.Column("value", sa.Numeric(), nullable=False, comment="Rate value"),
        sa.Column(
            "currency_datetime",
            sa.DateTime(),
            nullable=False,
            comment="Exchange rate date time",
        ),
        sa.Column(
            "last_update", sa.DateTime(), nullable=False, comment="Last date an update"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Represents an exchange rate",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate")
    # ### end Alembic commands ###
